version: '3.8'

services:
  api:
    build: ./api-node
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  frontend:
    build: ./frontend-react
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
    external: true