CREATE DATABASE monitor;
USE monitor;

CREATE TABLE cpu (     id INT AUTO_INCREMENT PRIMARY KEY,     free DOUBLE NOT NULL,     used DOUBLE NOT NULL );
CREATE TABLE ram (     id INT AUTO_INCREMENT PRIMARY KEY,     free DOUBLE NOT NULL,     used DOUBLE NOT NULL );