// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ObtenerMemoria() {
  return window['go']['main']['App']['ObtenerMemoria']();
}
